language: node_js

node_js:
 - "node"

cache: npm

script: npm run build

before_deploy:
- zip -r yureka-webservice dist/*
- mkdir -p deploy
- mv yureka-webservice.zip deploy/yureka-webservice.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: yureka-build-s3
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

deploy:
     provider: pages
     skip_cleanup: true
     github_token: $GH_TOKEN
     local_dir: docs
on:
     branch: master
