language: node_js

node_js:
 - "node"

cache: npm

script: npm run build

before_deploy:
- cd dist && zip -r yureka-webservice.zip ./*
- mkdir -p deploy
- mv yureka-webservice.zip deploy/yureka-webservice.zip

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yureka-build-s3
    key: yureka-webservice.zip
    bundle_type: zip
    application: yureka-webservice
    deployment_group: yureka-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true    
    on:
      branch: master
# test