language: node_js

node_js:
 - "node"

cache: npm

script: npm run build

before_deploy:
- rm -rf node_modules
- zip -r yureka-webservice.zip ./*
- mkdir -p deploy
- mv yureka-webservice.zip deploy/yureka-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yureka-build-s3
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yureka-build-s3
    key: yureka-webservice.zip
    bundle_type: zip
    deployment_group: yureka-webservice-group
    application: yureka-webservice
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: master